[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.6.0"

[prune]
  go-tests = true
  unused-packages = true
